package BuffersCorba;


/**
* BuffersCorba/boolArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from buffers.idl
* Sábado, 20 de Abril de 2019 09h19min27s BRT
*/

public final class boolArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public boolean value[] = null;

  public boolArrayHolder ()
  {
  }

  public boolArrayHolder (boolean[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BuffersCorba.boolArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BuffersCorba.boolArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BuffersCorba.boolArrayHelper.type ();
  }

}
