package BuffersCorba;


/**
* BuffersCorba/BuffersPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from buffers.idl
* Sábado, 20 de Abril de 2019 09h19min27s BRT
*/

public abstract class BuffersPOA extends org.omg.PortableServer.Servant
 implements BuffersCorba.BuffersOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getGarfo", new java.lang.Integer (0));
    _methods.put ("setGarfo", new java.lang.Integer (1));
    _methods.put ("getTentativa", new java.lang.Integer (2));
    _methods.put ("addTentativa", new java.lang.Integer (3));
    _methods.put ("setTentativa", new java.lang.Integer (4));
    _methods.put ("getSituacao", new java.lang.Integer (5));
    _methods.put ("setSituacao", new java.lang.Integer (6));
    _methods.put ("getGarfos", new java.lang.Integer (7));
    _methods.put ("getFilosofos", new java.lang.Integer (8));
    _methods.put ("getTentativas", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BuffersCorba/Buffers/getGarfo
       {
         int garfo = in.read_long ();
         boolean $result = false;
         $result = this.getGarfo (garfo);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // BuffersCorba/Buffers/setGarfo
       {
         int garfo = in.read_long ();
         boolean valor = in.read_boolean ();
         this.setGarfo (garfo, valor);
         out = $rh.createReply();
         break;
       }

       case 2:  // BuffersCorba/Buffers/getTentativa
       {
         int filosofo = in.read_long ();
         int $result = (int)0;
         $result = this.getTentativa (filosofo);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // BuffersCorba/Buffers/addTentativa
       {
         int filosofo = in.read_long ();
         this.addTentativa (filosofo);
         out = $rh.createReply();
         break;
       }

       case 4:  // BuffersCorba/Buffers/setTentativa
       {
         int filosofo = in.read_long ();
         int valor = in.read_long ();
         this.setTentativa (filosofo, valor);
         out = $rh.createReply();
         break;
       }

       case 5:  // BuffersCorba/Buffers/getSituacao
       {
         int filosofo = in.read_long ();
         int $result = (int)0;
         $result = this.getSituacao (filosofo);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // BuffersCorba/Buffers/setSituacao
       {
         int filosofo = in.read_long ();
         int valor = in.read_long ();
         this.setSituacao (filosofo, valor);
         out = $rh.createReply();
         break;
       }

       case 7:  // BuffersCorba/Buffers/getGarfos
       {
         boolean $result[] = null;
         $result = this.getGarfos ();
         out = $rh.createReply();
         BuffersCorba.boolArrayHelper.write (out, $result);
         break;
       }

       case 8:  // BuffersCorba/Buffers/getFilosofos
       {
         int $result[] = null;
         $result = this.getFilosofos ();
         out = $rh.createReply();
         BuffersCorba.longArrayHelper.write (out, $result);
         break;
       }

       case 9:  // BuffersCorba/Buffers/getTentativas
       {
         int $result[] = null;
         $result = this.getTentativas ();
         out = $rh.createReply();
         BuffersCorba.longArrayHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BuffersCorba/Buffers:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Buffers _this() 
  {
    return BuffersHelper.narrow(
    super._this_object());
  }

  public Buffers _this(org.omg.CORBA.ORB orb) 
  {
    return BuffersHelper.narrow(
    super._this_object(orb));
  }


} // class BuffersPOA
