package BuffersCorba;


/**
* BuffersCorba/Buffers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from buffers.idl
* Sábado, 20 de Abril de 2019 09h19min27s BRT
*/

public interface Buffers extends BuffersOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Buffers
