package BuffersCorba;


/**
* BuffersCorba/BuffersOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from buffers.idl
* Sábado, 20 de Abril de 2019 09h19min27s BRT
*/

public interface BuffersOperations 
{
  boolean getGarfo (int garfo);
  void setGarfo (int garfo, boolean valor);
  int getTentativa (int filosofo);
  void addTentativa (int filosofo);
  void setTentativa (int filosofo, int valor);
  int getSituacao (int filosofo);
  void setSituacao (int filosofo, int valor);
  boolean[] getGarfos ();
  int[] getFilosofos ();
  int[] getTentativas ();
} // interface BuffersOperations
