package BuffersCorba;


/**
* BuffersCorba/longArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from buffers.idl
* Sábado, 20 de Abril de 2019 09h19min27s BRT
*/

public final class longArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public longArrayHolder ()
  {
  }

  public longArrayHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BuffersCorba.longArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BuffersCorba.longArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BuffersCorba.longArrayHelper.type ();
  }

}
